# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa62934941022f33c624b093e81921ea95a9732f3ef094063e5bfe3deba788ab16d12086df08cd9794bc48aff91e27aa2b1252dd165d3d4d2026f9c8c9f30aa8

test:
  secret_key_base: bd5560f4c993ea8ed14d537bb5bd6fb728a7215d9319608d6da7ecee8cf3ca363b99013d80e984f8f495c316efe2a0ce77fc86fa6d2dba4fb543bd4a4340a3c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
